"""
Schema Normalizer
=================

This module implements the structural normalization stage of a
neuro-symbolic semantic compilation pipeline.

Its role is to transform the raw Intermediate Representation (IR)
generated by an LLM into a deterministic, well-formed structure
that can be safely consumed by downstream components.

The normalizer enforces a canonical schema format by:
- Ensuring the presence of all required fields
- Standardizing container types (lists, dicts)
- Replacing null or invalid values with safe defaults
- Eliminating structural ambiguity from LLM outputs

Important
---------
This module performs strictly structural normalization.

It does NOT:
- Validate semantic correctness
- Infer missing information
- Correct logical inconsistencies

Those responsibilities belong to later stages (e.g., SchemaValidator).

Pipeline
--------
LLM Output → SchemaNormalizer → SchemaValidator → CypherGenerator
"""

from typing import Dict, Any
import copy


class SchemaNormalizer:
    """
    Structural normalizer for the Intermediate Representation (IR).

    This component guarantees that the schema follows a stable and
    predictable format, regardless of variations or inconsistencies
    in LLM-generated outputs.

    By enforcing a canonical structure, it removes the need for
    defensive programming in downstream stages.
    """

    # Canonical schema structure expected by downstream components
    DEFAULT_SCHEMA = {
        "filters": [],
        "limit": None,
        "order_by": None,
        "path": [],
        "return_attributes": [],
        "target": {}
    }

    # --------------------------------------------------
    # Public API
    # --------------------------------------------------

    @classmethod
    def normalize(cls, ir: Dict[str, Any]) -> Dict[str, Any]:
        """
        Normalize a raw IR into a structurally consistent format.

        This method acts as the entry point of the normalization stage.
        It ensures that:
        - The IR is a valid dictionary
        - Top-level fields exist
        - The schema is present and structurally valid

        Any malformed or unexpected input is safely replaced with
        a default IR structure.

        Parameters
        ----------
        ir : Dict[str, Any]
            Raw intermediate representation produced by the LLM.

        Returns
        -------
        Dict[str, Any]
            Structurally normalized IR, guaranteed to follow the
            canonical schema format.
        """
        ir = copy.deepcopy(ir)

        # Fallback: completely invalid IR → return safe default
        if not isinstance(ir, dict):
            return cls._default_ir()

        # Ensure intent always exists
        ir.setdefault("user_intent", "retrieve")

        # Validate schema container
        schema = ir.get("schema")
        if not isinstance(schema, dict):
            ir["schema"] = copy.deepcopy(cls.DEFAULT_SCHEMA)
            return ir

        cls._normalize_schema(schema)

        return ir

    # --------------------------------------------------
    # Internal helpers
    # --------------------------------------------------

    @classmethod
    def _default_ir(cls) -> Dict[str, Any]:
        """
        Generate a fully valid default IR.

        Used as a fallback when the input IR is invalid or malformed.
        """
        return {
            "user_intent": "retrieve",
            "schema": copy.deepcopy(cls.DEFAULT_SCHEMA)
        }

    @classmethod
    def _normalize_schema(cls, schema: Dict[str, Any]) -> None:
        """
        Enforce canonical structure at the schema level.

        This method ensures:
        - All required fields exist
        - All fields match expected types
        - Invalid or null values are replaced with defaults

        It then delegates normalization to field-specific handlers.
        """

        # Enforce presence and type of all top-level schema fields
        for key, default in cls.DEFAULT_SCHEMA.items():
            if key not in schema or schema[key] is None:
                schema[key] = copy.deepcopy(default)
            elif not isinstance(schema[key], type(default)):
                schema[key] = copy.deepcopy(default)

        # Normalize individual components
        cls._normalize_filters(schema)
        cls._normalize_limit(schema)
        cls._normalize_order_by(schema)
        cls._normalize_path(schema)
        cls._normalize_return(schema)
        cls._normalize_target(schema)

    # --------------------------------------------------
    # Field normalizers
    # --------------------------------------------------

    @classmethod
    def _normalize_filters(cls, schema: Dict[str, Any]) -> None:
        """
        Normalize the 'filters' field into a list of canonical filter objects.

        Handles common LLM inconsistencies such as:
        - Single filter as dict instead of list
        - Invalid container types
        """

        filters = schema.get("filters") or []

        if isinstance(filters, dict):
            filters = [filters]

        if not isinstance(filters, list):
            filters = []

        schema["filters"] = [
            cls._normalize_filter(f) for f in filters
        ]

    @staticmethod
    def _normalize_filter(f: Dict[str, Any]) -> Dict[str, Any]:
        """
        Normalize a single filter object.

        Ensures all expected keys are present, even if missing in the input.
        Does not validate values or enforce semantic correctness.
        """

        if not isinstance(f, dict):
            return {
                "attribute": None,
                "node_label": None,
                "operator": None,
                "value_float": None,
                "value_int": None,
                "value_str": None,
            }

        return {
            "attribute": f.get("attribute"),
            "node_label": f.get("node_label"),
            "operator": f.get("operator"),
            "value_float": f.get("value_float"),
            "value_int": f.get("value_int"),
            "value_str": f.get("value_str"),
        }

    @staticmethod
    def _normalize_limit(schema: Dict[str, Any]) -> None:
        """
        Normalize the 'limit' field.

        Ensures the value is either an integer or None.
        """

        limit = schema.get("limit")

        if not isinstance(limit, int):
            schema["limit"] = None

    @staticmethod
    def _normalize_order_by(schema: Dict[str, Any]) -> None:
        """
        Normalize the 'order_by' field.

        Ensures the value is either a dictionary or None.
        """

        order_by = schema.get("order_by")

        if not isinstance(order_by, dict):
            schema["order_by"] = None

    @staticmethod
    def _normalize_path(schema: Dict[str, Any]) -> None:
        """
        Normalize the 'path' field.

        Ensures the value is always a list.
        """

        path = schema.get("path") or []

        if not isinstance(path, list):
            path = []

        schema["path"] = path

    @staticmethod
    def _normalize_return(schema: Dict[str, Any]) -> None:
        """
        Normalize the 'return_attributes' field.

        Ensures:
        - Always a list
        - All elements are strings
        """

        ret = schema.get("return_attributes") or []

        if isinstance(ret, str):
            ret = [ret]

        if not isinstance(ret, list):
            ret = []

        schema["return_attributes"] = [
            r for r in ret if isinstance(r, str)
        ]

    @staticmethod
    def _normalize_target(schema: Dict[str, Any]) -> None:
        """
        Normalize the 'target' field.

        Ensures:
        - Always a dictionary
        - Contains the 'label' key
        """

        target = schema.get("target") or {}

        if not isinstance(target, dict):
            target = {}

        target.setdefault("label", None)

        schema["target"] = target
